title: Business Analytics 
description: Examines the use of economic and statistical tools for making business decisions at an advanced level, and prepares students for future study in business analytics. Introduces programming for data analysis (no previous programming knowledge required) and links data analysis to decision making using both spreadsheet modeling and statistical programming. Topics include multiple regression, causal inference, forecasting, predictive analytics, machine learning, demand modeling, and optimization. Case studies apply advanced concepts to practical business problems. 
theme: just-the-docs

url: https://github.com/pharringtonp19/business-analytics

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
